const canvas = document.querySelector('#game');
const ctx = canvas.getContext('2d');
const $ = (id) => document.getElementById(id);
const keys = {}; let running = false, paused = false, score = 0, sector = 1, lives = 3, last = 0, spawn = 0;
const ship = { x: 480, y: 520, vx: 0, shots: [], cooldown: 0 };
let enemies = [], particles = [], stars = Array.from({ length: 130 }, () => ({ x: Math.random()*960, y: Math.random()*600, z: Math.random()*2+.2 }));
addEventListener('keydown', e => { keys[e.code] = true; if (e.code === 'Space') e.preventDefault(); if (e.code === 'KeyP' && running) togglePause(); });
addEventListener('keyup', e => keys[e.code] = false);
$('startButton').onclick = start; $('soundButton').onclick = () => $('soundButton').textContent = $('soundButton').textContent.includes('))') ? '◖×' : '◖))';
function start() { running=true; paused=false; score=0; sector=1; lives=3; enemies=[]; particles=[]; ship.x=480; ship.shots=[]; $('message').classList.add('hidden'); $('pauseCard').classList.add('hidden'); requestAnimationFrame(loop); }
function togglePause() { paused=!paused; $('pauseCard').classList.toggle('hidden', !paused); if (!paused) requestAnimationFrame(loop); }
function enemy() { enemies.push({x:80+Math.random()*800,y:-35,vy:1.05+sector*.13,r:17+Math.random()*10,hue:Math.random()>.65?'#ffcf5a':'#ff4f7d', phase:Math.random()*6.2}); }
function boom(x,y,color) { for(let i=0;i<20;i++) particles.push({x,y,vx:(Math.random()-.5)*5,vy:(Math.random()-.5)*5,life:1,color}); }
function update(dt) { const speed = .36*dt; ship.x += ((keys.ArrowLeft||keys.KeyA)?-speed:0)+((keys.ArrowRight||keys.KeyD)?speed:0); ship.x=Math.max(35,Math.min(925,ship.x)); ship.cooldown-=dt; if(keys.Space&&ship.cooldown<=0){ ship.shots.push({x:ship.x,y:492}); ship.cooldown=230; } spawn-=dt; if(spawn<=0){enemy();spawn=Math.max(280,980-sector*55);} ship.shots.forEach(s=>s.y-=.72*dt); ship.shots=ship.shots.filter(s=>s.y>-10); enemies.forEach(e=>{e.y+=e.vy*dt/16;e.x+=Math.sin(e.y/50+e.phase)*.7;});
 enemies = enemies.filter(e=> { for(const s of ship.shots) if(Math.hypot(s.x-e.x,s.y-e.y)<e.r+6){ s.y=-50; score+=100; boom(e.x,e.y,e.hue); return false; } if(e.y>550 && Math.abs(e.x-ship.x)<48){ lives--; boom(e.x,e.y,'#ff4f7d'); return false;} return e.y<630; }); particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.life-=dt/550;}); particles=particles.filter(p=>p.life>0); if(score>=sector*1000){sector++;} if(lives<=0) gameOver(); $('score').textContent=String(score).padStart(6,'0'); $('sector').textContent=String(sector).padStart(2,'0'); $('lives').textContent='◆ '.repeat(lives).trim() || '—'; }
function draw(){ ctx.fillStyle='#050a17';ctx.fillRect(0,0,960,600); const g=ctx.createRadialGradient(480,240,10,480,240,580);g.addColorStop(0,'#182953');g.addColorStop(1,'#030611');ctx.fillStyle=g;ctx.fillRect(0,0,960,600); stars.forEach(s=>{s.y+=s.z*.22;if(s.y>600)s.y=0;ctx.fillStyle=`rgba(185,230,255,${s.z/2.4})`;ctx.fillRect(s.x,s.y,s.z,s.z);}); ctx.strokeStyle='#68e8ff';ctx.shadowBlur=15;ctx.shadowColor='#48dfff';ship.shots.forEach(s=>{ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(s.x,s.y+16);ctx.stroke();}); enemies.forEach(e=>{ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.hue;ctx.shadowColor=e.hue;ctx.shadowBlur=15;ctx.beginPath();ctx.moveTo(0,e.r);ctx.lineTo(-e.r,e.r*.25);ctx.lineTo(-e.r*.5,-e.r);ctx.lineTo(e.r*.5,-e.r);ctx.lineTo(e.r,e.r*.25);ctx.closePath();ctx.fill();ctx.restore();}); particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,3,3);});ctx.globalAlpha=1;ctx.save();ctx.translate(ship.x,520);ctx.fillStyle='#b9f3ff';ctx.shadowColor='#39dfff';ctx.shadowBlur=25;ctx.beginPath();ctx.moveTo(0,-30);ctx.lineTo(-24,26);ctx.lineTo(0,16);ctx.lineTo(24,26);ctx.closePath();ctx.fill();ctx.fillStyle='#227cab';ctx.fillRect(-5,-17,10,27);ctx.restore();ctx.shadowBlur=0; }
function loop(time){if(!running||paused)return;const dt=Math.min(35,time-last||16);last=time;update(dt);draw();requestAnimationFrame(loop);} function gameOver(){running=false;$('message').classList.remove('hidden');$('message').querySelector('h1').innerHTML='MISSION<br /><em>LOST.</em>';$('startButton').innerHTML='TRY AGAIN <span>→</span>';}
draw();
